### ISSUE TITLE
Broken with Capistrano 3.7

### ISSUE THREAD

**Issue by mdesantis** [ekho/capistrano-git-submodule-strategy#17]
Related to issue #15. With Capistrano 3.7 I get the following error:

```
user@pc ~/app> cap -T --trace
cap aborted!
LoadError: cannot load such file -- capistrano/git
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/capistrano-git-submodule-strategy-fa678a8160c8/lib/capistrano/git-submodule-strategy.rb:1:in `require'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/capistrano-git-submodule-strategy-fa678a8160c8/lib/capistrano/git-submodule-strategy.rb:1:in `<top (required)>'
/home/user/app/Capfile:18:in `require'
/home/user/app/Capfile:18:in `<top (required)>'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.7.0/lib/capistrano/application.rb:14:in `run'
/home/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.7.0/bin/cap:3:in `<top (required)>'
/home/user/.asdf/installs/ruby/2.3.0/bin/cap:22:in `load'
/home/user/.asdf/installs/ruby/2.3.0/bin/cap:22:in `<main>'
/home/user/.asdf/installs/ruby/2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/user/.asdf/installs/ruby/2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ekho** [comment]
Try my new plugin [capistrano-git-with-submodules](https://github.com/ekho/capistrano-git-with-submodules)
